export default function DisclaimerPage() {
  return (
    <div className="max-w-4xl mx-auto py-10 prose prose-gray dark:prose-invert">
      <h1>Disclaimer</h1>
      <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
      
      <h2>1. Educational Purpose</h2>
      <p>This ATS & Interview Practice application is designed for educational and practice purposes only. It is not a substitute for professional career counseling or guaranteed job placement assistance.</p>
      
      <h2>2. ATS Scoring Accuracy</h2>
      <p>While our ATS scoring system is designed to simulate real-world Applicant Tracking Systems, actual ATS systems may vary significantly. Our scores and recommendations should be used as general guidance only.</p>
      
      <h2>3. AI-Generated Content</h2>
      <p>Cover letters, interview questions, and feedback generated by our AI systems are automated suggestions. Users should review and customize all content before use in actual job applications or interviews.</p>
      
      <h2>4. No Employment Guarantees</h2>
      <p>Use of this application does not guarantee job interviews, employment, or career advancement. Success in job searching depends on many factors beyond resume optimization and interview practice.</p>
      
      <h2>5. Third-Party Services</h2>
      <p>Our application integrates with third-party services including Google Gemini (Generative AI) and payment processors. We are not responsible for the availability or performance of these external services.</p>
      
      <h2>6. Technical Limitations</h2>
      <p>Resume parsing and analysis may not be 100% accurate for all document formats. Users should verify all extracted information and recommendations.</p>
      
      <h2>7. Industry Variations</h2>
      <p>Interview questions and ATS practices vary significantly across industries and companies. Our general recommendations may not apply to all specific situations.</p>
      
      <h2>8. Professional Advice</h2>
      <p>For specific career guidance, legal advice, or professional consultation, please consult with qualified professionals in your field or location.</p>
    </div>
  )
}
